// This file is automatically generated.
static const int SFX_COUNT = 13;
enum class Sfx {
    BOOT,
    CLICK,
    DREAM,
    FOOT,
    GROWL,
    GRUNT,
    HAA,
    LOCKED,
    OPEN,
    PLINK,
    UNLOCK,
    WAP,
    WHA
};
