// This file is automatically generated.
static const int SPRITE_COUNT = 1;
enum class Sprite {
    KNIGHT_1
};
static const int TILE_COUNT = 3;
enum class Tile {
    REAL_1,
    REAL_2,
    REAL_4
};
