// This file is automatically generated.
{ "sprite/knight_1", 0, 0, 32, 32, 16, 16 },
{ "tile/real_1", 0, 0, 32, 32, 16, 16 },
{ "tile/real_2", 0, 0, 32, 32, 16, 16 },
{ "tile/real_4", 0, 0, 32, 32, 16, 16 },
