// This file is automatically generated.
static const int SPRITE_COUNT = 16;
enum class Sprite {
    ACTION_DROP,
    ACTION_JUMP,
    ACTION_JUMPBACK,
    ACTION_TURN,
    ADVERSARY,
    DIALOG,
    DOOR_CLOSED,
    DOOR_LOCKED,
    DOOR_OPEN,
    GIRL,
    KEY,
    KNIGHT_1,
    PORTAL,
    SELECTION,
    TALKG1,
    TALKS1
};
static const int TILE_COUNT = 9;
enum class Tile {
    NONE,
    REAL_1,
    REAL_2,
    REAL_3,
    REAL_4,
    REAL_5,
    REAL_6,
    REAL_7,
    REAL_8
};
